## Create Keyspace
CREATE KEYSPACE moleads WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 3};
use moleads;

## Create tables
CREATE TABLE adjacency (id int, time timestamp, message text, actor_id text, actor_name text, target_id text, target_name text, PRIMARY KEY (actor_id, time), ) WITH CLUSTERING ORDER BY (time DESC);

CREATE TABLE word_counts (period text, time timestamp, word_count map<text, int>, PRIMARY KEY (period, time), ) WITH CLUSTERING ORDER BY (time DESC);
