## Create index with mapping

curl -XPUT 'http://localhost:9200/moleads' -d '
{"mappings": {
    "payment" : {
        "_all": {
            "enabled": false
        },
        "dynamic" : "strict",
        "properties" : {
            "id" : {
                "type" : "long",
                "index": "no"
             },
            "time" : {
                "type" : "date",
                "index": "no"
             },
            "message" : {
                "type" : "string",
                "index": "analyzed"
             },
            "actor_id" : {
                "type" : "string",
                "index": "no"
             },
            "actor_name" : {
                "type" : "string",
                "index": "no"
             },
            "target_id" : {
                "type" : "string",
                "index": "no"
             },
            "target_name" : {
                "type" : "string",
                "index": "no"
             }
        }
    }
 }
}'

curl -XPUT 'localhost:9200/moleads/_settings' -d '{"index" : {"refresh_interval" : "2s"} }'

/Optimizations for heavy indexing (see https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing)
- Need to set:
-- index.store.throttle.type to none
-- disable _all field in mappings (added to mapping setup)
-- Increase indices.memory.index_buffer_size from 10% (try 30%)
-- increase index.refresh_interval to 30s (-1 disables it entirely. Currently set to 2s).
-- increase index.translog.flush_threshold_size to 1GB (from 200MB)

## Index Stats
curl 'http://localhost:9200/moleads/_stats?level=shards'
- look for: indices.segments.index_writer_max_memory
